all:
  children:
    windows:
      hosts:
        ws2025-golden-image:
          ansible_host: 10.0.1.10
          ansible_user: azureadmin
          ansible_connection: winrm
          ansible_port: 5986
          ansible_winrm_server_cert_validation: ignore
